version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    environment:
      - DJANGO_SECRET_KEY=local
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DRF_RECAPTCHA_SECRET_KEY=${DRF_RECAPTCHA_SECRET_KEY}
      - APP_NAME=${APP_NAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               pip install -r requirements.txt &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
      # - "8002:8002"

    depends_on:
      - postgres
  # documentation:
  #   build: ./
  #   command: "mkdocs serve"
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "8001:8001"
