# fly.toml app configuration file generated for linkinback-worker on 2024-02-17T08:57:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linkinback-worker'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[processes]
  worker = 'celery -A linkin worker -l INFO'

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['worker']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
