# Generated by Django 4.0.4 on 2022-08-10 07:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('Social networks and online communities', 'Social networks and online communities'), ('News and media', 'News and media'), ('Search engines', 'Search engines'), ('Marketplace', 'Marketplace'), ('Adult', 'Adult'), ('Programming and developer software', 'Programming and developer software'), ('TV movies and streaming', 'TV movies and streaming'), ('Email', 'Email'), ('Blog', 'Blog'), ('Forum or wiki', 'Forum or wiki'), ('Business website', 'Business website'), ('Portfolio', 'Portfolio'), ('Crowdfunding', 'Crowdfunding'), ('Magazine', 'Magazine'), ('Educational', 'Educational')], max_length=200, null=True, verbose_name='Url category')),
                ('show_on_front', models.BooleanField(default=False)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='User description about this url (private)')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None, verbose_name='User tags')),
                ('category', models.CharField(blank=True, choices=[('Social networks and online communities', 'Social networks and online communities'), ('News and media', 'News and media'), ('Search engines', 'Search engines'), ('Marketplace', 'Marketplace'), ('Adult', 'Adult'), ('Programming and developer software', 'Programming and developer software'), ('TV movies and streaming', 'TV movies and streaming'), ('Email', 'Email'), ('Blog', 'Blog'), ('Forum or wiki', 'Forum or wiki'), ('Business website', 'Business website'), ('Portfolio', 'Portfolio'), ('Crowdfunding', 'Crowdfunding'), ('Magazine', 'Magazine'), ('Educational', 'Educational')], max_length=200, null=True, verbose_name='Url category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url.url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
