# Generated by Django 4.0.4 on 2022-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_category_url_title_alter_url_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
