# Generated by Django 4.0.4 on 2022-09-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_alter_url_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='show_on_front',
        ),
        migrations.AddField(
            model_name='url',
            name='hide_from_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='urluser',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
