name: Django CI

on:
  push:
    branches: [ "main", "test**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        export DJANGO_SECRET_KEY=tests
        python3 manage.py test --settings=linkin.config.test
